async function Module(moduleArg={}){var moduleRtn;var h=moduleArg,aa="./this.program",ba=import.meta.url,k="",ca;try{k=(new URL(".",ba)).href}catch{}ca=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);};var m=console.log.bind(console),q=console.error.bind(console),v,x=!1,da,ea,fa=!1;
function ha(){var a=y.buffer;z=new Int8Array(a);new Int16Array(a);A=new Uint8Array(a);new Uint16Array(a);h.HEAP32=new Int32Array(a);C=new Uint32Array(a);new Float32Array(a);new Float64Array(a);ia=new BigInt64Array(a);new BigUint64Array(a)}function D(a){h.onAbort?.(a);a=`Aborted(${a})`;q(a);x=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ea?.(a);throw a;}var E;
async function ka(a){if(!v)try{var b=await ca(a);return new Uint8Array(b)}catch{}if(a==E&&v)a=new Uint8Array(v);else throw"both async and sync fetching of the wasm failed";return a}async function la(a,b){try{var c=await ka(a);return await WebAssembly.instantiate(c,b)}catch(d){q(`failed to asynchronously prepare wasm: ${d}`),D(d)}}
async function ma(a){var b=E;if(!v)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){q(`wasm streaming compile failed: ${d}`),q("falling back to ArrayBuffer instantiation")}return la(b,a)}class na{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var ia,z,C,A,oa=a=>{for(;0<a.length;)a.shift()(h)},pa=[],qa=[],ra=()=>{var a=h.preRun.shift();qa.push(a)},sa=!0;
class ta{constructor(a){this.V=a-24}}
var ua=0,F=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},G={},va=()=>{if(!H){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",
LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:aa||"./this.program"},b;for(b in G)void 0===G[b]?delete a[b]:a[b]=G[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);H=c}return H},H,L=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},wa=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},
xa=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=wa(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},ya=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},za=()=>a=>(crypto.getRandomValues(a),0),Aa=a=>(Aa=za())(a),Ba=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:"/";if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=wa(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ca=globalThis.TextDecoder&&new TextDecoder,M=(a,b=0)=>{var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ca)return Ca.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):
(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Da=[],Ea=[];function Fa(a,b){Ea[a]={input:[],output:[],N:b};Ga(a,Ha)}
var Ha={open(a){var b=Ea[a.node.W];if(!b)throw new N(43);a.C=b;a.seekable=!1},close(a){a.C.N.S(a.C)},S(a){a.C.N.S(a.C)},read(a,b,c,d){if(!a.C||!a.C.N.fa)throw new N(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.N.fa(a.C)}catch(n){throw new N(29);}if(void 0===g&&0===e)throw new N(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.K=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.N.ca)throw new N(60);try{for(var e=0;e<d;e++)a.C.N.ca(a.C,b[c+e])}catch(f){throw new N(29);}d&&(a.node.D=a.node.B=
Date.now());return e}},Ia={fa(){a:{if(!Da.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){var b=null;break a}b=Array(L(a)+1);a=F(a,b,0,b.length);b.length=a;Da=b}b=Da.shift()}return b},ca(a,b){null===b||10===b?(m(M(a.output)),a.output=[]):0!=b&&a.output.push(b)},S(a){0<a.output?.length&&(m(M(a.output)),a.output=[])},Da(){return{wa:25856,ya:5,va:191,xa:35387,ua:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Ea(){return 0},
Fa(){return[24,80]}},Ja={ca(a,b){null===b||10===b?(q(M(a.output)),a.output=[]):0!=b&&a.output.push(b)},S(a){0<a.output?.length&&(q(M(a.output)),a.output=[])}},O={G:null,I(){return O.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new N(63);O.G||(O.G={dir:{node:{J:O.s.J,H:O.s.H,P:O.s.P,T:O.s.T,ka:O.s.ka,ma:O.s.ma,la:O.s.la,da:O.s.da,Y:O.s.Y},stream:{F:O.u.F}},file:{node:{J:O.s.J,H:O.s.H},stream:{F:O.u.F,read:O.u.read,write:O.u.write,ha:O.u.ha,ja:O.u.ja}},
link:{node:{J:O.s.J,H:O.s.H,R:O.s.R},stream:{}},ea:{node:{J:O.s.J,H:O.s.H},stream:Ka}});c=La(a,b,c,d);16384===(c.mode&61440)?(c.s=O.G.dir.node,c.u=O.G.dir.stream,c.v={}):32768===(c.mode&61440)?(c.s=O.G.file.node,c.u=O.G.file.stream,c.A=0,c.v=O.oa??(O.oa=new Uint8Array(0))):40960===(c.mode&61440)?(c.s=O.G.link.node,c.u=O.G.link.stream):8192===(c.mode&61440)&&(c.s=O.G.ea.node,c.u=O.G.ea.stream);c.K=c.D=c.B=Date.now();a&&(a.v[b]=c,a.K=a.D=a.B=c.K);return c},s:{J(a){var b={};b.za=8192===(a.mode&61440)?
a.id:1;b.Ca=a.id;b.mode=a.mode;b.Ga=1;b.uid=0;b.Ba=0;b.W=a.W;16384===(a.mode&61440)?b.size=4096:32768===(a.mode&61440)?b.size=a.A:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.K=new Date(a.K);b.D=new Date(a.D);b.B=new Date(a.B);b.na=4096;b.ta=Math.ceil(b.size/b.na);return b},H(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.A!=b&&(c=a.v,a.v=new Uint8Array(b),a.v.set(c.subarray(0,Math.min(b,a.A))),a.A=b))},P(){O.Z||(O.Z=new N(44),O.Z.stack=
"<generic error, no stack>");throw O.Z;},T(a,b,c,d){return O.createNode(a,b,c,d)},ka(a,b,c){try{var d=P(b,c)}catch(f){}if(d){if(16384===(a.mode&61440))for(var e in d.v)throw new N(55);e=Ma(d.parent.id,d.name);if(Q[e]===d)Q[e]=d.M;else for(e=Q[e];e;){if(e.M===d){e.M=d.M;break}e=e.M}}delete a.parent.v[a.name];b.v[c]=a;a.name=c;b.B=b.D=a.parent.B=a.parent.D=Date.now()},ma(a,b){delete a.v[b];a.B=a.D=Date.now()},la(a,b){var c=P(a,b),d;for(d in c.v)throw new N(55);delete a.v[b];a.B=a.D=Date.now()},da(a){return[".",
"..",...Object.keys(a.v)]},Y(a,b,c){a=O.createNode(a,b,41471,0);a.link=c;return a},R(a){if(40960!==(a.mode&61440))throw new N(28);return a.link}},u:{read(a,b,c,d,e){if(e>=a.node.A)return 0;d=Math.min(a.node.A-e,d);b.set(a.node.v.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===z.buffer&&(f=!1);if(!d)return 0;a=a.node;a.D=a.B=Date.now();if(f)a.v=b.subarray(c,c+d),a.A=d;else if(0===a.A&&0===e)a.v=b.slice(c,c+d),a.A=d;else{f=e+d;var g=a.v.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>
0),g&&(f=Math.max(f,256)),g=a.v.subarray(0,a.A),a.v=new Uint8Array(f),a.v.set(g));a.v.set(b.subarray(c,c+d),e);a.A=Math.max(a.A,e+d)}return d},F(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.A);if(0>b)throw new N(28);return b},ha(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new N(43);a=a.node.v;if(e&2||a.buffer!==z.buffer){d=!0;D();e=void 0;if(!e)throw new N(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);z.set(a,e)}}else d=
!1,e=a.byteOffset;return{V:e,sa:d}},ja(a,b,c,d){O.u.write(a,b,0,d,c,!1);return 0}}},Na=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},Oa=null,Pa={},R=[],Qa=1,Q=null,Ra=!1,Sa=!0,N=class{name="ErrnoError";constructor(a){this.O=a}},Ta=class{X={};node=null;get flags(){return this.X.flags}set flags(a){this.X.flags=a}get position(){return this.X.position}set position(a){this.X.position=a}},Ua=class{s={};u={};U=null;constructor(a,b,c,d){a||=this;this.parent=a;this.I=a.I;this.id=Qa++;this.name=b;this.mode=
c;this.W=d;this.K=this.D=this.B=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}};
function S(a,b={}){if(!a)throw new N(44);b.aa??(b.aa=!0);"/"===a.charAt(0)||(a="//"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(n=>!!n);for(var d=Oa,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if("."!==a[f])if(".."===a[f])if(e=ya(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=xa(e+"/"+a[f]);try{d=P(d,a[f])}catch(n){if(44===n?.O&&g&&b.qa)return{path:e};throw n;}!d.U||g&&!b.aa||(d=d.U.root);if(40960===(d.mode&61440)&&(!g||b.$)){if(!d.s.R)throw new N(52);
d=d.s.R(d);"/"===d.charAt(0)||(d=ya(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new N(32);}function Ma(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Q.length}function P(a,b){var c=16384===(a.mode&61440)?(c=T(a,"x"))?c:a.s.P?0:2:54;if(c)throw new N(c);for(c=Q[Ma(a.id,b)];c;c=c.M){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.s.P(a,b)}
function La(a,b,c,d){a=new Ua(a,b,c,d);b=Ma(a.parent.id,a.name);a.M=Q[b];return Q[b]=a}function T(a,b){return Sa?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Va(a,b){if(16384!==(a.mode&61440))return 54;try{return P(a,b),20}catch(c){}return T(a,"wx")}function U(a){a=R[a];if(!a)throw new N(8);return a}
function Wa(a,b){var c=null?.u.H,d=c?null:a;c??=a.s.H;if(!c)throw new N(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new N(22);throw e;}}var Ka={open(a){a.u=Pa[a.node.W].u;a.u.open?.(a)},F(){throw new N(70);}};function Ga(a,b){Pa[a]={u:b}}
function Xa(a,b){var c="/"===b;if(c&&Oa)throw new N(10);if(!c&&b){var d=S(b,{aa:!1});b=d.path;d=d.node;if(d.U)throw new N(10);if(16384!==(d.mode&61440))throw new N(54);}b={type:a,Ha:{},ia:b,pa:[]};a=a.I(b);a.I=b;b.root=a;c?Oa=a:d&&(d.U=b,d.I&&d.I.pa.push(b))}function Ya(a,b,c){var d=S(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new N(28);if("."===a||".."===a)throw new N(20);var e=Va(d,a);if(e)throw new N(e);if(!d.s.T)throw new N(63);return d.s.T(d,a,b,c)}
function V(a){return Ya(a,16895,0)}function W(a,b,c){"undefined"==typeof c&&(c=b,b=438);Ya(a,b|8192,c)}function Za(a,b){if(!Ba(a))throw new N(44);var c=S(b,{parent:!0}).node;if(!c)throw new N(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Va(c,b);if(d)throw new N(d);if(!c.s.Y)throw new N(63);c.s.Y(c,b,a)}
function $a(a,b){if(""===a)throw new N(44);if("string"==typeof b){var c={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof c)throw Error(`Unknown file open mode: ${b}`);b=c}c=b&64?33206:0;if("object"==typeof a)var d=a;else{var e=a.endsWith("/");var f=S(a,{$:!(b&131072),qa:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new N(20);}else{if(e)throw new N(31);d=Ya(a,c|511,0);f=!0}if(!d)throw new N(44);8192===(d.mode&61440)&&(b&=-513);if(b&65536&&16384!==(d.mode&61440))throw new N(54);
if(!f&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=16384===(d.mode&61440)&&("r"!==e||b&576)?31:T(d,e)):e=44,e))throw new N(e);if(b&512&&!f){e=d;e="string"==typeof e?S(e,{$:!0}).node:e;if(16384===(e.mode&61440))throw new N(31);if(32768!==(e.mode&61440))throw new N(28);if(a=T(e,"w"))throw new N(a);Wa(e,{size:0,timestamp:Date.now()})}a:for(e=d;;){if(e===e.parent){e=e.I.ia;var g=g?"/"!==e[e.length-1]?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:e.name;e=e.parent}b={node:d,
path:g,flags:b&-131713,seekable:!0,position:0,u:d.u,ra:[],error:!1};g=-1;b=Object.assign(new Ta,b);if(-1==g)a:{for(g=0;4096>=g;g++)if(!R[g])break a;throw new N(33);}b.L=g;R[g]=b;b.u.open&&b.u.open(b);f&&(c&=511,d="string"==typeof d?S(d,{$:!0}).node:d,Wa(d,{mode:c&4095|d.mode&-4096,B:Date.now(),Aa:void 0}))}function ab(a,b,c){if(null===a.L)throw new N(8);if(!a.seekable||!a.u.F)throw new N(70);if(0!=c&&1!=c&&2!=c)throw new N(28);a.position=a.u.F(a,b,c);a.ra=[]}
function X(a,b,c){a=xa("/dev/"+a);var d=Na(!!b,!!c);X.ga??(X.ga=64);var e=X.ga++<<8|0;Ga(e,{open(f){f.seekable=!1},close(){c?.buffer?.length&&c(10)},read(f,g,n,r){for(var l=0,p=0;p<r;p++){try{var t=b()}catch(u){throw new N(29);}if(void 0===t&&0===l)throw new N(6);if(null===t||void 0===t)break;l++;g[n+p]=t}l&&(f.node.K=Date.now());return l},write(f,g,n,r){for(var l=0;l<r;l++)try{c(g[n+l])}catch(p){throw new N(29);}r&&(f.node.D=f.node.B=Date.now());return l}});W(a,d,e)}
var Y={},eb=(a,b,c,d)=>{var e={string:l=>{var p=0;if(null!==l&&void 0!==l&&0!==l){p=L(l)+1;var t=bb(p);F(l,A,t,p);p=t}return p},array:l=>{var p=bb(l.length);z.set(l,p);return p}};a=h["_"+a];var f=[],g=0;if(d)for(var n=0;n<d.length;n++){var r=e[c[n]];r?(0===g&&(g=cb()),f[n]=r(d[n])):f[n]=d[n]}c=a(...f);return c=function(l){0!==g&&db(g);return"string"===b?l?M(A,l):"":"boolean"===b?!!l:l}(c)};Q=Array(4096);Xa(O,"/");V("/tmp");V("/home");V("/home/web_user");
(function(){V("/dev");Ga(259,{read:()=>0,write:(d,e,f,g)=>g,F:()=>0});W("/dev/null",259);Fa(1280,Ia);Fa(1536,Ja);W("/dev/tty",1280);W("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Aa(a),b=a.byteLength);return a[--b]};X("random",c);X("urandom",c);V("/dev/shm");V("/dev/shm/tmp")})();
(function(){V("/proc");var a=V("/proc/self");V("/proc/self/fd");Xa({I(){var b=La(a,"fd",16895,73);b.u={F:O.u.F};b.s={P(c,d){c=+d;var e=U(c);c={parent:null,I:{ia:"fake"},s:{R:()=>e.path},id:c+1};return c.parent=c},da(){return Array.from(R.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();h.noExitRuntime&&(sa=h.noExitRuntime);h.print&&(m=h.print);h.printErr&&(q=h.printErr);h.wasmBinary&&(v=h.wasmBinary);h.thisProgram&&(aa=h.thisProgram);
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();h.ccall=eb;h.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?h["_"+a]:(...f)=>eb(a,b,c,f,d)};
var fb,db,bb,cb,y,gb={i:(a,b,c)=>{a=new ta(a);C[a.V+16>>2]=0;C[a.V+4>>2]=b;C[a.V+8>>2]=c;ua++;D()},d:()=>D(""),h:a=>{var b=A.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-y.buffer.byteLength+65535)/65536|0;try{y.grow(d);ha();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},b:(a,b)=>{var c=0,d=0,e;for(e of va()){var f=b+c;C[a+d>>2]=f;c+=F(e,A,f,Infinity)+1;d+=4}return 0},
c:(a,b)=>{var c=va();C[a>>2]=c.length;a=0;for(var d of c)a+=L(d)+1;C[b>>2]=a;return 0},e:function(a){try{var b=U(a);if(null===b.L)throw new N(8);b.ba&&(b.ba=null);try{b.u.close&&b.u.close(b)}catch(c){throw c;}finally{R[b.L]=null}b.L=null;return 0}catch(c){if("undefined"==typeof Y||"ErrnoError"!==c.name)throw c;return c.O}},f:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var n=C[a>>2],r=C[a+4>>2];a+=8;var l=e,p=n,t=r,u=f,ja=z;if(0>t||0>u)throw new N(28);if(null===l.L)throw new N(8);
if(1===(l.flags&2097155))throw new N(8);if(16384===(l.node.mode&61440))throw new N(31);if(!l.u.read)throw new N(28);var I="undefined"!=typeof u;if(!I)u=l.position;else if(!l.seekable)throw new N(70);var J=l.u.read(l,ja,p,t,u);I||(l.position+=J);var w=J;if(0>w){var K=-1;break a}b+=w;if(w<r)break;"undefined"!=typeof f&&(f+=w)}K=b}C[d>>2]=K;return 0}catch(B){if("undefined"==typeof Y||"ErrnoError"!==B.name)throw B;return B.O}},g:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);
try{if(isNaN(b))return 22;var e=U(a);ab(e,b,c);ia[d>>3]=BigInt(e.position);e.ba&&0===b&&0===c&&(e.ba=null);return 0}catch(f){if("undefined"==typeof Y||"ErrnoError"!==f.name)throw f;return f.O}},a:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var f,g=b=0;g<c;g++){var n=C[a>>2],r=C[a+4>>2];a+=8;var l=e,p=n,t=r,u=f,ja=z;if(0>t||0>u)throw new N(28);if(null===l.L)throw new N(8);if(0===(l.flags&2097155))throw new N(8);if(16384===(l.node.mode&61440))throw new N(31);if(!l.u.write)throw new N(28);l.seekable&&
l.flags&1024&&ab(l,0,2);var I="undefined"!=typeof u;if(!I)u=l.position;else if(!l.seekable)throw new N(70);var J=l.u.write(l,ja,p,t,u,void 0);I||(l.position+=J);var w=J;if(0>w){var K=-1;break a}b+=w;if(w<r)break;"undefined"!=typeof f&&(f+=w)}K=b}C[d>>2]=K;return 0}catch(B){if("undefined"==typeof Y||"ErrnoError"!==B.name)throw B;return B.O}}},Z;
Z=await (async function(){function a(c){c=Z=c.exports;h._start_simulation=c.l;fb=h._main=c.m;h._malloc=c.n;h._free=c.o;db=c.p;bb=c.q;cb=c.r;y=c.j;ha();return Z}var b={a:gb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});E??=h.locateFile?h.locateFile?h.locateFile("engine.wasm",k):k+"engine.wasm":(new URL("engine.wasm",import.meta.url)).href;return a((await ma(b)).instance)}());
(function(){function a(){h.calledRun=!0;if(!x){fa=!0;if(!h.noFSInit&&!Ra){var b,c;Ra=!0;b??=h.stdin;c??=h.stdout;d??=h.stderr;b?X("stdin",b):Za("/dev/tty","/dev/stdin");c?X("stdout",null,c):Za("/dev/tty","/dev/stdout");d?X("stderr",null,d):Za("/dev/tty1","/dev/stderr");$a("/dev/stdin",0);$a("/dev/stdout",1);$a("/dev/stderr",1)}Z.k();Sa=!1;da?.(h);h.onRuntimeInitialized?.();if(!h.noInitialRun){var d=fb;try{var e=d(0,0);sa||(h.onExit?.(e),x=!0);throw new na(e);}catch(f){if(!(f instanceof na||"unwind"==
f))throw f;}}if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;)e=h.postRun.shift(),pa.push(e);oa(pa)}}if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ra();oa(qa);h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()})();fa?moduleRtn=h:moduleRtn=new Promise((a,b)=>{da=a;ea=b});
;return moduleRtn}export default Module;
